<?php

require_once dirname(__FILE__).'/../bootstrap.php';

/**
 * Test class for Eav.
 * Generated by PHPUnit on 2010-02-06 at 18:57:25.
 */
class EavTest extends DatabaseTestCase
{
    /**
     * @var    Eav
     * @access protected
     */
    protected $_eav;

    /**
     * Entity model
     * @var Zend_Db_Table
     * @access protected
     */
    protected $_entityTable;

    protected function getDataSet()
    {
        return $this->createXMLDataSet(TESTS_PATH . '/fixtures/eav.xml');
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        parent::setUp();
        $entityTable = new Zend_Db_Table('eav_entity');
        $entityTable->setRowClass('Eav_Row');
        $this->_entityTable = $entityTable;

        $this->_eav = new Eav($entityTable);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
        parent::tearDown();
        $pdo = $this->getDatabaseTester()->getConnection()->getConnection();
        $pdo->exec("DELETE FROM eav_entity;");
        $pdo->exec("DELETE FROM eav_entity_int;");
        $pdo->exec("DELETE FROM eav_entity_decimal;");
        $pdo->exec("DELETE FROM eav_entity_string;");
        $pdo->exec("DELETE FROM eav_entity_text;");
        $pdo->exec("DELETE FROM eav_attribute;");
    }

    public function testGetTableName()
    {
        $tableName = $this->_eav->getTableName($this->_entityTable);
        $this->assertEquals('eav_entity', $tableName);
    }

    public function testGetEavTableName()
    {
        $this->assertEquals('eav_entity_int', $this->_eav->getEavTableName('int'));
        $this->assertEquals('eav_entity_string', $this->_eav->getEavTableName('string'));
    }

    public function testGetEavModel()
    {
        $attribute = $this->_eav->getAttribute('secname');
        $eavModel = $this->_eav->getEavModel($attribute);
        $this->assertTrue($eavModel instanceof Zend_Db_Table);

        $tableName = $this->_eav->getEavTableName($attribute->type);
        $this->assertEquals($tableName, $eavModel->info('name'));
    }

    /**
     * @todo Implement testGetEavModels().
     */
    public function testGetEavModels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testGetAttributeType()
    {
        $attribute = $this->_eav->getAttribute('secname');
        $this->assertEquals('string', $this->_eav->getAttributeType($attribute));
    }

    public function testGetAttributeId()
    {
        $attribute = $this->_eav->getAttribute('secname');
        $this->assertEquals(1, $this->_eav->getAttributeId($attribute));
    }

    public function testGetAttributeName()
    {
        $attribute = $this->_eav->getAttribute('secname');
        $this->assertEquals('secname', $this->_eav->getAttributeName($attribute));
    }

    public function testGetEntityId()
    {
        $entity = $this->_entityTable->find(1)->current();
        $this->assertEquals(1, $this->_eav->getEntityId($entity));
    }

    public function testGetAttribute()
    {
        $attribute = $this->_eav->getAttribute('secname');
        $this->assertTrue($attribute instanceof Zend_Db_Table_Row);
        $this->assertEquals('secname', $attribute->name);
    }

    /**
     * @todo Implement testCacheAttribute().
     */
    public function testCacheAttribute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testCacheAttributes().
     */
    public function testCacheAttributes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testGetAttributeValue()
    {
        $row = $this->_entityTable->find(1)->current();
        $secname = $this->_eav->getAttributeValue($row, 'secname');
        $this->assertEquals('one secname', $secname);

        $row = $this->_entityTable->find(2)->current();
        $secname = $this->_eav->getAttributeValue($row, 'secname');
        $this->assertEquals('two secname', $secname);
        
        $row = $this->_entityTable->find(3)->current();
        $secname = $this->_eav->getAttributeValue($row, 'secname');
        $this->assertEquals('', $secname);
    }

    public function testSetAttributeValue()
    {
        $attribute = $this->_eav->getAttribute('secname');
        $row = $this->_entityTable->find(1)->current();
        
        $values = array('changed', 'changed2');
        foreach ($values as $value) {
            $this->_eav->setAttributeValue($row, $attribute, $value);
            $storedValue = $this->_eav->getAttributeValue($row, $attribute, true);
            $this->assertEquals($value, $storedValue);
        }
    }

    public function testLoadAttributes()
    {
        $rows = $this->_entityTable->fetchAll();
        $attributes = array();
        $attributes[] = $this->_eav->getAttribute('secname');
        $attributes[] = $this->_eav->getAttribute('age');

        $data = $this->_eav->loadAttributes($rows, $attributes);

        $this->assertTrue(is_array($data));
    }
}